	
var translationsEN= {
    home: 'ಮುಖ್ಯ ಪುಟ್ಟ ',
    project: 'ಯೋಜನೆ',
    involve: 'ಭಾಗವಹಿಸಿ',
	involve_dot: 'ಭಾಗವಹಿಸಿ....',
	gallery :'ಚಿತ್ರಶಾಲೆ ಮತ್ತು ಲೇಖನ',
	ratha:'ತ್ವೌಳವ ಮಧ್ವ ರಥ ಯಾತ್ರೆ',
	spiritual:'ಆಧ್ಯಾತ್ಮಿಕ ಚಿಂತನೆಗಳು',
	social:'ಸಾಂಸ್ಕೃತಿಕ  ಕಾರ್ಯಾಕ್ರಮಗಳು',
	matrimony:'ತ್ವೌಮಓ ವಧು ವರ ವೇದಿಕೆ',
	vidyanidhi:'ತ್ವೌಮಓ ವಿದ್ಯಾ ನಿಧಿ',
	Volunteer:'ಸ್ವಯಂಸೇವಕರಾಗಿ',
	Member:'ಸದಸ್ಯರಾಗಿ',
	imagegallery:'ಚಿತ್ರಶಾಲೆ',
	videogallery: 'Video Gallery',
	discussion:'ಜಿಜ್ಞಾಸೆ ಮತ್ತು ಲೇಖನ',
	download:'ಡೌನ್ಲೋಡ್',
	audio:'ಕೃತಿ ಮತ್ತು ಪದ್ಯಕೋಶ',
	social_title:'ತ್ವೌಳವ ಮಧ್ವ ಓಕ್ಕೂಟವು ಯಕ್ಷಗಾನ, ಹಿಂಮೇಳಗಾನ, ನೃತ್ಯ ಹೀಗೆ ತನ್ನದೆ ರೀತಿಯಲ್ಲಿ ಸಂಸ್ಕ್ರುತಿಕ ಚಟುವಟಿಕೆಯಲ್ಲಿ ತೊಡಗಿಸಿಕೊಂಡಿದೆ',
	spiritual_title:'ತ್ವೌಳವ ಮಧ್ವ ಓಕ್ಕೂಟವು ಭಜನೆ, ಪಾರಯಣ, ಪಾಠ, ಹಲವು ವಿದ್ವಾಂಸರಿಂದ ಪ್ರವಚನ ಹೀಗೆ ಹಲವು ಕಾರ್ಯಾಕ್ರಮಗಳನ್ನು ಏರ್ಪಡಿಸಿ ಆಧ್ಯಾತ್ಮಿಕ ಲೋಕವನ್ನು ಸಾಮಾನ್ಯರಿಗೆ ಪರಿಚಯಸಿದೆ',
	matrimony_title :'ತ್ವೌಳವ ಮಧ್ವ ಓಕ್ಕೂಟವು  ಪುರೋಹಿತ ಹಾಗೂ ಬಡ ಬ್ರಹ್ಮಣರ ವಧು ಮತ್ತು ವರರಿಗೆ ಶ್ರೀ ಸುಗುಣೇಂದ್ರ ತೀರ್ಥರ ಆಶೀರ್ವಾದೊಂದಿಗೆ ಉಚಿತ ವೇದಿಕೆಯನ್ನು ಕಲ್ಪಿಸಿದೆ',
	padma_purana:'ಪದ್ಮ ಪುರಾಣ ',
	purandara:'ಪುರಂದರ ದಾಸರು',
	wonder_book:'ದಿ ವನ್ಡರ್ ಆಫ್ ದಿ ವರ್ಲ್ಡ',
	vargese:'ಲೆೇಖಕ ವರ್ಗೀಸ್ ಅಮೇರಿಕ',
	vishwesha:'ತ್ವೌಳವ ಮಧ್ವ ಓಕ್ಕೂಟವು ಆಧ್ಯಾತ್ಮಿಕ ಮತ್ತು ಮಧ್ವ ಸಂಸ್ಕ್ರತಿಯನ್ನು ಉಳಿಸಿ ಹಾಗೂ ಅಭಿರುದ್ದಿಗೊಳಿಸಲು ಮಹತ್ವರ ಪಾತ್ರ ವಹಿಸಿಕೊಂಡಿದೆ.ಅದು ತನ್ನದೇ ಆದ ರೀತಿಯಲ್ಲಿ ಕೊಡುಗೆ ನೀಡಿದೆ.',
	vishwesha_name:'ಶ್ರೀ ವಿಶ್ವೇಶ ತೀರ್ಥರು',
	sugendra_name:'ಸುಗುಣೇಂದ್ರ ತೀರ್ಥ',
	bannajje_name:'ಬನ್ನಂಜೆ ಗೋವಿಂದಾಚಾರ್ಯ',
	sugendra:'ತ್ವೌಳವ ಮಧ್ವ ಓಕ್ಕೂಟವು ಎಲ್ಲಾ ಮಧ್ವ ಬ್ರಾಹ್ಮಣನ್ನು ತುಳು ಒಗ್ಗೂಡಿಸಿ ಮಧ್ವ ಸಂಪ್ರಾದಯವನ್ನು ಮತ್ತಷ್ತ್ಟು ಮೆರಗುಗೊಳಿಸುವ ಕಾರ್ಯಮಾಡಬೇಕಾಗಿದೆ. ಈ ನಿಟ್ಟಿನಲ್ಲಿ ನಾನು ನನ್ನ ಸಂಪುರ್ಣ ಬೆಂಬಲವನ್ನು ಹಾಗು ಸಹಕಾರವನ್ನು ಕೊಡುತ್ತಿದ್ದೇನೆ',
	bannajje:'ತ್ವೌಳವ ಮಧ್ವ ಓಕ್ಕೂಟವು ತತ್ವವಾದ ಹಾಗೂ ಮಧ್ವ ಸಿದ್ದಾಂತ ಪ್ರಸಾರ ಮನೆ ಮನೆಗೆ ತಲಪುವ ಕಾರ್ಯ ಮಾಡಬೇಕಿದೆ.',
	ratha_home:'ಜನರಲ್ಲಿ ಮಧ್ವ ಸಿದ್ದಾಂತದ ಜಾಗ್ರತಿ ಮತ್ತು ಸಂಸ್ಕ್ರುತಿಯ ಮಹತ್ವವನ್ನು ಪ್ರಸ್ತುತಗೊಳಿಸಲು ತ್ವೌಳವ ಮಧ್ವ ರಥ ಯಾತ್ರೆಯನ್ನು ಪ್ರತಿ ತಿಂಗಳು ನಿಮ್ಮ ಮನೆಯಲ್ಲಿ',
	read_more:'ಮತ್ತಷ್ಟು',
	paurohitya:'ಪೌರೋಹಿತ್ಯ',
	join:'ಸದಸ್ಯರಾಗಿ',
	peetadeepathi:'ಪೀಠಾಧೀಪತಿ',
	pejawara:'ಪೇಜಾವರ ಅದೋಕ್ಷಜ ಮಠ',
	udupi:'ಉಡುಪಿ',
	puttige:' ಪೀಠಾಧೀಪತಿ ಪುತ್ತಿಗೆ  ಮಠ',
	schoolar:'ವಿದ್ವಾಂಸರು',
	anandamala:'ಆನಂದಮಲಾ',
	down_home:'ಉಚಿತ ಆಡಿಯೊ, ಪಿಡಿಫ್ ಹಾಗೂ ವಿಡಿಯೊಗಾಗಿ ',
	down_button:'ಇದನ್ನು ಒತ್ತಿ',
	vidya_home:'ಮದ್ವ ಬ್ರಾಹ್ಮಣ ಬಡ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ತ್ವೌಳವ ಮಧ್ವ ಓಕ್ಕೂಟದ ಪರವಾಗಿ ವಿದ್ಯಾ ನಿಧಿ',
	down_home_full:'ನಿಮ್ಮ ಮೆಚ್ಚಿನ ಮಧ್ವ ವಿಜಯ, ಸಂದ್ಯಾವಂದನೆ, ಸ್ತೋತ್ರಾಸ್ ,ವೇದ ,ಉಪನಿಷತ್ ಮುಂತಾದ ಉಚಿತ ಆಡಿಯೊ, ಪಿಡಿಫ್ ಹಾಗೂ ವಿಡಿಯೊಗಾಗಿ',
	latest_work:'ನಮ್ಮ ಇತ್ತೀಚಿನ ಕೆಲಸ',
	navigates:'ಸಂಚರಿಸು',
	events:'ಕಾರ್ಯಕ್ರಮಗಳು',
	about:'ನಮ್ಮ ಬಗ್ಗೆ',
	sitemap:'ಸೈಟ್ಮ್ಯಾಪ್',
	terms:'ಬಳಕೆಯ ನಿಯಮಗಳು',
	address:'ವಿಳಾಸ',
	phone:'ದೂರವಾಣಿ',
	mail:'ಇಮೇಲ್',
	tmo_address:'#524,10th C  ಮುಖ್ಯ ರಸ್ತೆ ,AGB ಲೇಔಟ್, Opposite ಹೆಸರಘಟ್ಟ ರಸ್ತೆ, ಚಿಕ್ಕಸಂದ್ರ ಪೋಸ್ಟ್ ಬೆಂಗಳೂರು-560090',
	contact:'ಸಂಪರ್ಕಿಸಿ',
	contacts:'ಸಂಪರ್ಕಿಸಿ',
	stay:'ಸದಾ ನಮ್ಮೊಂದಿಗಿರಿ',
	ratha_yathre:'ರಥ ಯಾತ್ರೆ'
};

var translationsKA= {
    home: 'Home',
    project: 'Project',
    involve: 'Get Invloved',
	involve_dot:'Get Involve....',
	gallery :'Gallery And Article',
	ratha:'Taulava Madhwa Ratha Yathre',
	spiritual:'Spiritual Activity',
	social:'Socio-Cultural Activity',
	matrimony:'TMO Matrimony',
	vidyanidhi:'TMO Vidya Nidhi',
	Member:'As a Member',
	Volunteer:'As An Volunteer',
	imagegallery:'Image Gallery',
	videogallery: 'Video Gallery',
	discussion:'Discussion and Forums',
	download:'Download',
	audio:'Audio Gallery',
	social_title:'TMO has been actively organizing social cultural activities like Yakshagana,Himmela classes',
	spiritual_title:'TMO has been conducting several activities to convert words into action, through Parayana, Bhajane, Paata and Pravachana by scholars TMO tries to erdicate the ignorance of society!',
	matrimony_title :'Taulava Maadhwa Okkkotta is working	towards Marriage alliance to community\'s eligible bachelors under guidance of Parama Poojya Sri Sri Sugunendra Theertha swamiji	of Puttige',
	padma_purana:'Padma Purana',
	purandara:'Purandara Dasaru',
	wonder_book:'The Wonder of The World',
	vargese: 'Author Varghese',
	vishwesha:'TMO played important role in creating spiritual awareness and enrich spiritual values by way of Parayana,Bhajane and Pravachanas in Taulava Madhwa families.',
	sugendra:'TMO continuesly contribution in  propagation of Vedic studies and bring an order to the perception and with an intention of long standing objects in mind and involving all other Madhwa Tulu community.',
	bannajje:'TMO should work on unify our community(shivalli madhwas) members under one roof, preach tatvaada. ',
	ratha_home:'To create and enrich spiritual values by way of Parayana,Bhajane in spiritual centers and residences of Shivalli madhwas on weekly and monthly.',
	read_more:'Read More',
	paurohitya:'Paurohitya',
	join:'Join Now',
	vishwesha_name:'H.H Śrī  Viśhvēśha Thērthāru',
	sugendra_name:'Sri Sri Sugunēndrā Thērthāru',
	bannajje_name:'Dr Bannan̄je Gōvindācāryara',
	peetadeepathi:'Peetadeepathi',
	pejawara:'Pejavara-adokshja Matta',
	udupi:'Udupi',
	puttige:'Puttige Matta',
	schoolar:'Schoolar',
	anandamala:'Anandamala',
	down_home:'It\'s free to download pdf,audio and video from gallery',
	down_button:'Download here',
	vidya_home:'The Association has been in the lime light since inception, with the several useful programs of interest to its community by helping poor families',
	down_home_full:'Download and view your favourite video,audios and photos of SuMadhwa Vijaya,Sandhya vandana, Stotras ,Veda ,Upanishat and Puraana etc..',
	latest_work:'Our Latest Work',
	navigates:'Navigate',
	events:'Events',
	about:'About Us',
	sitemap:'Sitemap',
	terms:'Terms of Use',
	address:'Address',
	phone:'Phone',
	mail:'Email',
	tmo_address:' #524,10th C Main, AGB layout, Opp Hesaraghatta Road, Chikkasandra Post, Bengaloru-560090',
	contact:'Contact Us',
	contacts:'Contact',
	stay:'Stay Connected',
	ratha_yathre:'Ratha Yathre'
};